spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /pizzeria/users/v3/api-docs
        name: User Service
      - url: /pizzeria/menu/v3/api-docs
        name: Menu Service
      - url: /pizzeria/orders/v3/api-docs
        name: Order Service